name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies 
        run:  sudo apt-get install libgtest-dev
      - name: build project
        run: cmake -B build && cd build/ && cmake --build .
      
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
            name: build
            path: build/
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: build
      
      - run: ls -la
      - name: run tests
        run: cd build/test/ && ./test_matrix 
        
        
