name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies 
        run:  sudo apt-get install libgtest-dev
      - name: build project
        run: cd scripts/ && bash build.sh
        
      - run: ls -la 
      
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
            name: build
            path: matrix_calc/
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: build
  
      - run: ls -la
      
      - name: run tests
        run: cd scripts && bash tests.sh
        
        
