name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run : echo "testing"