name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies 
        run:  sudo apt-get install libgtest-dev lcov
      - name: build project
        run: cd scripts/ && bash build.sh
        
      - run: ls -la 
      
      - name: upload lib
        uses: actions/upload-artifact@v3
        with:
            name: libmatrix_calculator
            path: ./build/libmatrix_calculator.a
            
      - name: upload tests
        uses: actions/upload-artifact@v3
        with:
            name: test_matrix_lib
            path: ./build/test/test_matrix_lib
            
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download libmatrix_calculator
        uses: actions/download-artifact@v3
        with:
          name: libmatrix_calculator
          
      - name: download test_matrix_lib
        uses: actions/download-artifact@v3
        with:
          name: test_matrix_lib
  
      - run: ls -la
    
      - name: run tests
        run: chmod +x ./test_matrix_lib && ./test_matrix_lib

